[package]
name = "runty8"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "*"
rand = "*"
runty8-runtime = {path = "../runty8-runtime" }
winit = "0.26"
glium = { version  = "*", optional = true }

[features]
glium = ["dep:glium"]
