[workspace]
members = [
  "src/runty8",
  "src/runty8-core",
  "src/runty8-editor",
  "src/runty8-event-loop",
  "src/runty8-winit",
  "examples/standalone-game",
  "examples/moving-box",
]
default-members = ["src/runty8"]
