[workspace]
members = [
  "src/runty8",
  "src/runty8-runtime",
  "src/runty8-run",
  "src/runty8-event-loop",
  "src/runty8-web",
  "src/runty8-winit",
  "examples/standalone-game",
]
default-members = ["src/runty8"]
