[package]
name = "runty8-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
runty8-core = { path = "../runty8-core" }
runty8-winit = { path = "../runty8-winit" }
runty8-event-loop = { path = "../runty8-event-loop" }
itertools = "*"
rand = "*"
winit = "0.26"
glium = "0.31"
instant = "0.1"
