[package]
name = "runty8-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
itertools = "*"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "*", features = ["js"] }
