[package]
name = "runty8-winit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runty8-runtime = { path = "../runty8-runtime" }
winit = "0.26"
