on: push

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.63.0 # Current rustc on my machine
    steps:
      - uses: actions/checkout@v2
        name: Checkout source

      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --workspace --exclude=runty8-event-loop

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --workspace --exclude=runty8-event-loop

      - uses: actions-rs/cargo@v1
        name: Format
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: --workspace --exclude=runty8-event-loop -- -D warnings -A unknown_lints
